package roborally.utilities.enums;

public enum PhaseStep {
    REVEAL_CARDS,
    MOVE_ROBOTS,
    MOVE_ALL_CONVEYOUR_BELTS,
    MOVE_EXPRESS_CONVEYOR_BELTS,
    MOVE_COGS,
    FIRE_LASERS,
    UPDATE_CHECKPOINT,
    REGISTER_FLAG_POSITION,
    CHECK_FOR_WINNER,
    NULL_PHASE
}
